globals:
  checkr:
    skip: <%= ENV['SKIP_CHECKR'] %>
    auth: <%= ENV['CHECKRIO_AUTH'] %>
    package: <%= ENV['CHECKRIO_PACKAGE'] %>
  surveymonkey:
    site:
      ssl: true
      host: www.surveymonkey.com
      path_base: s
    api:
      ssl: true
      host: api.surveymonkey.net
      path_base: v2
  createsend:
    api_key: <%= ENV['CREATESEND_API_KEY'] %>
    mentor_list_id: <%= ENV['CREATESEND_MENTOR_LIST_ID'] %>
    teacher_list_id: <%= ENV['CREATESEND_TEACHER_LIST_ID'] %>
    student_list_id: <%= ENV['CREATESEND_STUDENT_LIST_ID'] %>
  registration:
    open: <%= ENV['REGISTRATION_OPEN'] %>
    override_username: <%= ENV['REGISTRATION_OVERRIDE_USERNAME'] %>
    override_password: <%= ENV['REGISTRATION_OVERRIDE_PASSWORD'] %>
development:
  surveys:
    token: paTBz61kMlD0mPWrsaHR3921EuYbHlBvqU0GDZQ.5nahBvB1GbdZpbh2WnOzXY4SmOei5qZUPMyUoVk7k9hAexHW2kJzm49cMPSLQyLL.Ts=
    key: kyum5g4der94mm7zm2rv849p
    required:
      student: 
        url_id: P2DF7F5
        id: "60623500"
      mentor: 
        url_id: P2DF7F5
        id: "60623500"
      coach: 
        url_id: P2DF7F5
        id: "60623500"
production:
  surveys:
    token: <%= ENV['SURVEYMONKEY_TOKEN'] %>
    key: <%= ENV['SURVEYMONKEY_KEY'] %>
    required:
      student: 
        url_id: <%= ENV['STUDENT_SURVEYMONKEY_COLLECTOR']%>
        id: "<%= ENV['STUDENT_SURVEYMONKEY_SURVEY_ID'] %>"
      mentor: 
        url_id: <%= ENV['MENTOR_SURVEYMONKEY_COLLECTOR']%>
        id: "<%= ENV['MENTOR_SURVEYMONKEY_SURVEY_ID'] %>"
      coach: 
        url_id: <%= ENV['COACH_SURVEYMONKEY_COLLECTOR']%>
        id: "<%= ENV['COACH_SURVEYMONKEY_SURVEY_ID'] %>"